---
mywin1:
 hosts:
   Win-Rahul
vars:
   ansible_user: administrator
   ansible_password: ntms321#
   ansible_winrm_transport: ntlm
   ansible_connection: winrm
   ansible_port: 5986
   ansible_winrm_server_cert_validation: ignore

...